ALTER TABLE "CommunityPost"
ADD COLUMN "editedAt" TIMESTAMP(3);

ALTER TABLE "CommunityComment"
ADD COLUMN "editedAt" TIMESTAMP(3);

ALTER TABLE "CommunityPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CommunityComment" ENABLE ROW LEVEL SECURITY;
