export const notificationPriority = {
  ACTIVITY_ASSIGNED: 2,
  ACTIVITY_DEADLINE: 2,
  ANNOUNCEMENT: 2,
  BADGE_AWARDED: 5,
  COMMENT_REPLY: 3,
  FEEDBACK_RECEIVED: 3,
  FOLLOWED_TOPIC_ACTIVITY: 2,
  GROUP_INVITATION: 3,
  GROUP_POST: 2,
  LEARNING_CONTENT_ASSIGNED: 3,
  LESSON_AVAILABLE: 1,
  MENTION: 4,
  MODULE_AVAILABLE: 1,
  TOPIC_COMMENT: 2,
} as const;

export const notificationPreferenceForType = {
  MENTION: "mentions",
  COMMENT_REPLY: "commentReplies",
  TOPIC_COMMENT: "topicComments",
  FOLLOWED_TOPIC_ACTIVITY: "followedTopicActivity",
  LESSON_AVAILABLE: "lessonAvailable",
  MODULE_AVAILABLE: "moduleAvailable",
  ACTIVITY_ASSIGNED: "activityAssigned",
  FEEDBACK_RECEIVED: "feedbackReceived",
  ACTIVITY_DEADLINE: "activityDeadline",
  ANNOUNCEMENT: "announcements",
  GROUP_INVITATION: "groupInvitations",
  GROUP_POST: "groupPosts",
  LEARNING_CONTENT_ASSIGNED: "contentAssignments",
} as const;

export const notificationTitleForType = {
  MENTION: "Você foi mencionado",
  COMMENT_REPLY: "Nova resposta ao seu comentário",
  TOPIC_COMMENT: "Novo comentário no seu tópico",
  FOLLOWED_TOPIC_ACTIVITY: "Nova atividade em uma discussão seguida",
  LESSON_AVAILABLE: "Nova aula disponível",
  MODULE_AVAILABLE: "Novo módulo disponível",
  ACTIVITY_ASSIGNED: "Nova atividade para você",
  FEEDBACK_RECEIVED: "Você recebeu feedback",
  ACTIVITY_DEADLINE: "Prazo de atividade se aproximando",
  ANNOUNCEMENT: "Novo comunicado",
  BADGE_AWARDED: "Nova conquista desbloqueada",
  GROUP_INVITATION: "Convite para grupo de estudo",
  GROUP_POST: "Nova publicação em um grupo de estudo",
  LEARNING_CONTENT_ASSIGNED: "Novo conteúdo para você",
} as const;
